ErM = (input('Would you like to ENCRYPT english (E) or DECODE Molch(M)'))
if ErM == 'M':
    Molch = str(input('Please Enter Your Molch here'))

    result = Molch.replace('"^', 'z')
    Molch = result
    result = Molch.replace('"%', 'y')
    Molch = result
    result = Molch.replace('"$', 'x')
    Molch = result
    result = Molch.replace('"£', 'w')
    Molch = result
    result = Molch.replace('""', 'v')
    Molch = result
    result = Molch.replace('"!', 'u')
    Molch = result
    result = Molch.replace('")', 't')
    Molch = result
    result = Molch.replace('!(', 's')
    Molch = result
    result = Molch.replace('!*', 'r')
    Molch = result
    result = Molch.replace('!&', 'q')
    Molch = result
    result = Molch.replace('!^', 'p')
    Molch = result
    result = Molch.replace('!%', 'o')
    Molch = result
    result = Molch.replace('!$', 'n')
    Molch = result
    result = Molch.replace('!£', 'm')
    Molch = result
    result = Molch.replace('!"', 'l')
    Molch = result
    result = Molch.replace('!!', 'k')
    Molch = result
    result = Molch.replace('!)', 'j')
    Molch = result
    result = Molch.replace('(', 'i')
    Molch = result
    result = Molch.replace('*', 'h')
    Molch = result
    result = Molch.replace('&', 'g')
    Molch = result
    result = Molch.replace('^', 'f')
    Molch = result
    result = Molch.replace('%', 'e')
    Molch = result
    result = Molch.replace('$', 'd')
    Molch = result
    result = Molch.replace('£', 'c')
    Molch = result
    result = Molch.replace('"', 'b')
    Molch = result
    result = Molch.replace('!', 'a')
    Molch = result

    result = Molch.replace('@', '')
    Molch = result
    result = Molch.replace('#', ' ')
    Molch = result

    print(result)

else:
    Molch = str(input('Please Enter Your English here'))

    result = Molch.replace('z', '"^')
    Molch = result
    result = Molch.replace('y', '"%')
    Molch = result
    result = Molch.replace('x', '"$')
    Molch = result
    result = Molch.replace('w', '"£')
    Molch = result
    result = Molch.replace('v', '""')
    Molch = result
    result = Molch.replace('u', '"!')
    Molch = result
    result = Molch.replace('t', '")')
    Molch = result
    result = Molch.replace('s', '!(')
    Molch = result
    result = Molch.replace('r', '!*')
    Molch = result
    result = Molch.replace('q', '!&')
    Molch = result
    result = Molch.replace('p', '!^')
    Molch = result
    result = Molch.replace('o', '!%')
    Molch = result
    result = Molch.replace('n', '!$')
    Molch = result
    result = Molch.replace('m', '!£')
    Molch = result
    result = Molch.replace('l', '!"')
    Molch = result
    result = Molch.replace('k', '!!')
    Molch = result
    result = Molch.replace('j', '!)')
    Molch = result
    result = Molch.replace('i', '(')
    Molch = result
    result = Molch.replace('h', '*')
    Molch = result
    result = Molch.replace('g', '&')
    Molch = result
    result = Molch.replace('f', '^')
    Molch = result
    result = Molch.replace('e', '%')
    Molch = result
    result = Molch.replace('d', '$')
    Molch = result
    result = Molch.replace('c', '£')
    Molch = result
    result = Molch.replace('b', '"')
    Molch = result
    result = Molch.replace('a', '!')
    Molch = result
    print(Molch)
